### ISSUE TITLE
[Bug] Error after `lru` update from `0.7.0` to `0.7.1`

### ISSUE THREAD

**Issue by alexmozaidze** [lukexor/pix-engine#8]
Version `0.5.0` and higher doesn't compile, however  `0.4.2` works just fine.
```rust
error[E0499]: cannot borrow `*self` as mutable more than once at a time
   --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/pix-engine-0.5.1/src/ops.rs:400:17
    |
397 |         for item in self.iter_mut() {
    |                     ---------------
    |                     |
    |                     first mutable borrow occurs here
    |                     first borrow later used here
...
400 |                 self.pop(key);
    |                 ^^^^^^^^^^^^^ second mutable borrow occurs here

For more information about this error, try `rustc --explain E0499`.
error: could not compile `pix-engine` due to previous error
```

**Comment by lukexor** [comment]
Very odd since the pipeline passes just fine. The recent failure was due to a breaking change in nightly with must_use that should be fixed by now. Either way I agree this should be failing and no clue how it got missed.

**Comment by alexmozaidze** [comment]
I don't understand still. When I clone the tic tac toe project I did with `0.5` version of Pix, it works perfectly fine, but in the new project it just doesn't work, and I don't understand why, I even did `rustup update` and changed toolchain to stable but it's no use, the error is still *only* in the new projects I make, but not the old ones.

**Comment by alexmozaidze** [comment]
Oh wait, when I delete `Cargo.lock` on tic tac toe project it stops compiling and gives the same error

**Comment by alexmozaidze** [comment]
I did a diff on 2 `Cargo.lock`s, here's the diff: https://www.diffchecker.com/QRAq8Hai
There seem to be 3 crates that updated, reverting them fixes the issue.
Update: it seems that `lru` update from `0.7.0` to `0.7.1` was causing the issue (not 100% sure though)

**Comment by alexmozaidze** [comment]
`Cargo.toml` has `lru = "0.7.0"`, which means that it'll pick `0.7.*` version of `lru`. Can you set `lru` version to `=0.7.0` or `=0.7.1`?

**Comment by lukexor** [comment]
Thanks for catching the root cause. One of the perils of relying on the implicit internal behavior of a crate. Seems like they changed something that broke the implementation in a patch version.

I'll just fix the usage to make it work on future diversions of lru
